### ISSUE TITLE
Run mocha in headless mode for CI

### ISSUE THREAD

**Issue by JessicaSachs** [JessicaSachs/vite-component-test-starter#3]

**Comment by aelbore** [comment]
@JessicaSachs 
Headless run the test (zero config)
https://github.com/aelbore/vite-component-test-starter

some of code is coming from this repository, i just add createServer function to run the server programatically.

**Comment by JessicaSachs** [comment]
This is great! Can you submit a PR with a version that contains both the headless task _and_ the tdd task?

**Comment by aelbore** [comment]
> This is great! Can you submit a PR with a version that contains both the headless task _and_ the tdd task?

Sure Please see my PR #5
